
languageCode = 'en-us'
title = 'Panduza - Dev Zone'

[module]
    # replacements = "github.com/Panduza/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/Panduza/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
    unsafe = true

